config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :stories

  root 'stories#index'

end

app/models/frequency.rb
# == Schema Information
#
# Table name: frequencies
#
#  id          :integer          not null, primary key
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  days        :integer
#  how_often   :integer          default("1")
#

class Frequency < ActiveRecord::Base
  has_many :schedules
end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id           :integer          not null, primary key
#  story_id     :integer
#  frequency_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_schedules_on_frequency_id  (frequency_id)
#  index_schedules_on_story_id      (story_id)
#

class Schedule < ActiveRecord::Base
  belongs_to :story
  belongs_to :frequency
end

app/models/story.rb
# == Schema Information
#
# Table name: stories
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  points      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Story < ActiveRecord::Base
  has_one :schedule
  validates_presence_of :title, :points
  validates_numericality_of :points, :less_than_or_equal_to => 13, :greater_than => 0
  has_one :frequency, through: :schedule
  has_many :tasks
end

app/models/story_frequency.rb
# == Schema Information
#
# Table name: stories_frequencies
#
#  id           :integer          not null, primary key
#  story_id     :integer
#  frequency_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_stories_frequencies_on_frequency_id  (frequency_id)
#  index_stories_frequencies_on_story_id      (story_id)
#

class StoryFrequency < ActiveRecord::Base
  belongs_to :story
  belongs_to :frequency
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  description :string
#  story_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_tasks_on_story_id  (story_id)
#

class Task < ActiveRecord::Base
  belongs_to :story
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @frequency = Frequency.find_by(id: 2)
    @story = Story.first

    if @story.schedule
      @story.frequency = @frequency
    else
      @story.create_schedule(frequency: @frequency)
    end

    @message = @story.frequency
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  before_action :set_selected_frequency, only: [:create, :update]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @story.create_schedule(frequency: @selected_frequency)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        @story.frequency = @selected_frequency
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :description, :points).merge({description: 'foobar'})
    end

  def set_selected_frequency
    @selected_frequency = Frequency.find_by(id: params[:story][:frequency])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= @message.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MemeMachine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
    <% if @story.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

          <ul>
            <% @story.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, rows: 8, cols: 40 %>
    </div>
    <div class="field">
      <%= f.label :frequency %>
      <% if @story.new_record? %>
          <%= f.collection_select :frequency, Frequency.all, :id, :description %>
      <% else %>
          <%= f.collection_select :frequency, Frequency.all, :id, :description, {selected: @story.frequency.id} %>
      <% end %>
    </div>
    <div class="field">
      <%= f.label :points %><br>
      <%= f.number_field :points, min: 1, max: 13 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Points</th>
      <th>Frequency</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.description %></td>
        <td><%= story.points %></td>
        <td><%= story.frequency.description %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @story.description %>
</p>

<p>
  <strong>Points:</strong>
  <%= @story.points %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>